resolver: lts-14.0
packages:
  - asterius
  - binaryen
  - ghc-toolkit
  - inline-js/inline-js-core
  - npm-utils
  - wabt
  - wasm-toolkit
ghc-build: standard
setup-info:
  ghc:
    linux64:
      8.6.5:
        url: https://6218-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: 3fb0667f5412b660b62a828d171dcab2f8c225f83376b2147532297cb10c07f1
    macosx:
      8.6.5:
        url: https://6220-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        sha256: 2d694689b5cd099ec4729672cfec07ff09a037d38b913b49a5d016f81c7affb9
